openapi: 3.0.0
info:
  version: "1.0.0"
  title: App1 API
servers:
  - url: http://localhost:8080/app1
paths:
  /app1/items:
    get:
      summary: Ottieni una lista di items
      operationId: getItems
      responses:
        '200':
          description: Successful operation, this is a list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/itemDto'
  /app1/newItems:
    post:
      summary: Creare un nuovo item
      operationId: createItem
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/itemDto'
      responses:
        '201':
          description: Item creato
  /app1/updateItem:
    put:
      summary: Updates an existing one
      operationId: updateItem
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/itemDto'
      responses:
        '201':
          description: Item aggiornato
  /app1/deleteItem:
    delete:
      operationId: deleteItem
      parameters:
        - in: query
          name: itemId
          description: ID of the item to retrieve
          required: true
          schema:
            type: int
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/itemDto'
components:
  schemas:
    itemDto:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
